name: tuyage
description: "Tuyage like whatsapp"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  country_picker: ^2.0.26
  firebase_core: ^3.6.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  photo_manager: ^3.2.3
  flutter_contacts: ^1.1.9+2
  url_launcher: ^6.3.0
  firebase_database: ^11.0.4
  page_transition: ^2.1.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  uuid: ^4.4.2
  custom_clippers: ^2.0.0
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  emoji_picker_flutter: ^3.1.0
  video_player: ^2.6.0
  enough_giphy_flutter: ^0.4.1
  flutter_sound: ^9.16.2
  path_provider: ^2.1.4
  permission_handler: ^11.0.0
  audioplayers: ^6.1.0
  swipe_to: ^1.0.6
  story_view: ^0.16.5
  agora_uikit: ^1.3.10
  collection: ^1.18.0
  sqflite: ^2.4.0
  path: ^1.9.0
  firebase_messaging: ^15.1.3


dependency_overrides:
  enough_platform_widgets: ^1.1.1
  flutter_platform_widgets: ^7.0.1

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#111B21"
  image: assets/images/splash_light.png
  image_dark: assets/images/splash_dark.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#111B21"
    image: assets/images/splash_light.png
    image_dark: assets/images/splash_dark.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#111B21"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:


  uses-material-design: true


  assets:
    - assets/images/
