// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBplK7pFCRWISVXyXuh__9O8s8cxWXiEPk',
    appId: '1:770228086066:web:ebf0a47f20631337c0232b',
    messagingSenderId: '770228086066',
    projectId: 'tuyage-barundi',
    authDomain: 'tuyage-barundi.firebaseapp.com',
    databaseURL: 'https://tuyage-barundi-default-rtdb.firebaseio.com',
    storageBucket: 'tuyage-barundi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyjaeU31N-v3kYZ8ZwTreX41gkXH3UA-g',
    appId: '1:770228086066:android:921d839730f50ac3c0232b',
    messagingSenderId: '770228086066',
    projectId: 'tuyage-barundi',
    databaseURL: 'https://tuyage-barundi-default-rtdb.firebaseio.com',
    storageBucket: 'tuyage-barundi.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBplK7pFCRWISVXyXuh__9O8s8cxWXiEPk',
    appId: '1:770228086066:web:7bb89b2b494a38ffc0232b',
    messagingSenderId: '770228086066',
    projectId: 'tuyage-barundi',
    authDomain: 'tuyage-barundi.firebaseapp.com',
    databaseURL: 'https://tuyage-barundi-default-rtdb.firebaseio.com',
    storageBucket: 'tuyage-barundi.appspot.com',
  );
}
