name: Firebase App Distribution

on:
  push:
    branches:
      - master  # Utiliser la branche master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Ajouté ici pour spécifier la distribution

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # Assurez-vous que cette version est correcte

      - name: Clean Build
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      

      - name: Build APK
        run: flutter build apk --release --stacktrace

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Upload to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
          TESTER_EMAILS: ${{ secrets.TESTER_EMAILS }}
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app $ANDROID_APP_ID \
          --testers $TESTER_EMAILS
