name: Firebase App Distribution

on:
  push:
    branches:
      - master  # Utiliser la branche master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.26.0' # Assurez-vous que cette version est correcte

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Upload to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
          TESTER_EMAILS: ${{ secrets.TESTER_EMAILS }}
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app $ANDROID_APP_ID \
          --testers $TESTER_EMAILS
